name: eureka
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.9.7
    - asdf[version='>=2.7.1,<2.11.0'] # Needed for jwst==1.3.3
    - astropy
    - batman-package
    - bokeh
    - ccdproc
    - codecov # Required for testing
    - corner
    - cython
    - dynesty[version='>1.0']
    - emcee[version='>3.0.0']
    - flake8 # Required for testing
    - george
    - gwcs
    - h5py
    - ipykernel # Required for jupyter
    - ipython
    - jupyter # Required for jupyter
    - lmfit
    - matplotlib
    - mkl-service
    - nbsphinx # Needed for documentation
    - nb_conda_kernels # Required for jupyter
    - numpy[version='>=1.20.0,<1.22']
    - pandas
    - photutils
    - pip # required for the pip installs below
    - pytest # Required for testing
    - pytest-cov # Required for testing
    - pytest-doctestplus # Required for testing
    - recommonmark # Needed for documentation
    - requests
    - scipy[version='>=1.4.0'] # Needed for scipy.fft
    - tqdm
    - pip:
        - crds
        - exoplanet
        - image_registration
        - jwst==1.3.3
        - myst-parser # Needed for documentation
        - pymc3
        - sphinx-rtd-theme # Needed for documentation
        - starry>=1
        - stcal
        - stdatamodels
        - svo_filters
        - theano-pymc

