name: Blank Issue
description: Submit an issue that doesn't fall into any other category
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error traceback output
      description: If relevant, please copy and paste the full traceback of any errors you encountered.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kevin218/Eureka/blob/main/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
