name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
body:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: instrument
    attributes:
      label: Instrument
      description: Which instrument or piece of code were you running?
      multiple: true
      options:
        - NIRISS (Stages 1-3)
        - NIRSpec (Stages 1-3)
        - NIRCam (Stages 1-3)
        - MIRI (Stages 1-3)
        - Light curve fitting (Stages 4-6)
        - Other
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true