name: Enhancement Suggestion
description: Suggest an enhancement to Eureka!
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: instrument
    attributes:
      label: Instrument
      description: Which instrument or piece of code would you like to see improved?
      multiple: true
      options:
        - NIRISS (Stages 1-3)
        - NIRSpec (Stages 1-3)
        - NIRCam (Stages 1-3)
        - MIRI (Stages 1-3)
        - Light curve fitting (Stages 4-6)
        - Other (any stage)
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: What is your suggestion?
      description: What feature would you like to see in Eureka?
      placeholder: It would be super helpful if Eureka! did...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error traceback output
      description: If relevant, please copy and paste the full traceback of any errors you encountered.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kevin218/Eureka/blob/main/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
